### ISSUE TITLE
Server segfault when interrupted on Linux

### ISSUE THREAD

**Issue by Kbz-8** [DigitalPulseSoftware/ThisSpaceOfMine#9]
ThisServerOfMine raises a segmentation fault when interrupted by a CTRL+C on Linux, here are the logs from GDB :

```text
server ready.
Peer connected (outgoing: false, peerIndex: 0, address: IpAddress([::1]:49448), data: 0)
Auth request from Mingebag (version 0.2.2)
Mingebag authenticated
Peer disconnected (peerIndex: 0, data: 0)
^Creceived interruption signal Interrupt, exiting...
[Thread 0x7ffff1e006c0 (LWP 20157) exited]

Thread 1 "ThisServerOfMin" received signal SIGSEGV, Segmentation fault.
0x00007ffff7f1cbb9 in tsom::ChunkEntities::~ChunkEntities() () from /home/kbz_8/Downloads/TSOM/libTSOMCommon.so
(gdb) bt
#0  0x00007ffff7f1cbb9 in tsom::ChunkEntities::~ChunkEntities() () from /home/kbz_8/Downloads/TSOM/libTSOMCommon.so
#1  0x00007ffff7f92cc8 in tsom::ServerInstance::~ServerInstance() () from /home/kbz_8/Downloads/TSOM/libTSOMServer.so
#2  0x00007ffff7f8f4e5 in tsom::ServerInstanceAppComponent::~ServerInstanceAppComponent() () from /home/kbz_8/Downloads/TSOM/libTSOMServer.so
#3  0x0000555555557cdb in ?? ()
#4  0x0000555555559898 in ?? ()
#5  0x00007ffff7443cd0 in __libc_start_call_main (main=main@entry=0x555555557870, argc=argc@entry=1, argv=argv@entry=0x7fffffffdf58) at ../sysdeps/nptl/libc_start_call_main.h:58
#6  0x00007ffff7443d8a in __libc_start_main_impl (main=0x555555557870, argc=1, argv=0x7fffffffdf58, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffdf48) at ../csu/libc-start.c:360
#7  0x00005555555578d5 in ?? ()
(gdb) 
```

TSOM version : 0.2.2
OS : ArchLinux

**Comment by SirLynix** [comment]
This is now fixed, let me know if it happens again.
